name: Continuous Integration

on:
  push:

jobs:
  build-deps-image:
    uses: ./.github/workflows/build-deps-image.yaml
    permissions:
      contents: read
      packages: write

  ci:
    name: Lint and build
    needs: build-deps-image
    runs-on: ubuntu-latest
    container:
      {#- Escape curly braces for Cookiecutter. -#}
      {%- raw %}
      image: ${{ needs.build-deps-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      {%- endraw %}

    steps:
      - name: Configure git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Checkout repository
        {#- Escape curly braces for Cookiecutter. -#}
        {%- raw %}
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        {%- endraw %}
        run: |
          git init -b main
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${GITHUB_SHA}"
          git checkout FETCH_HEAD

      - name: Lint code
        run: ./workflow.cmd lint

      - name: Build package
        run: ./workflow.cmd build

  test:
    name: Test (Python {%- raw %}${{ matrix.python-version }}{%- endraw %})
    needs: build-deps-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
{%- for version in cookiecutter._known_python_versions %}
{%- if version >= cookiecutter.min_python_version and version <= cookiecutter.max_python_version %}
          - "{{ version }}"
{%- endif %}
{%- endfor %}
    container:
      {#- Escape curly braces for Cookiecutter. -#}
      {%- raw %}
      image: ${{ needs.build-deps-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      {%- endraw %}

    steps:
      - name: Configure git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Checkout repository
        {#- Escape curly braces for Cookiecutter. -#}
        {%- raw %}
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        {%- endraw %}
        run: |
          git init -b main
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git fetch --depth=1 origin "${GITHUB_SHA}"
          git checkout FETCH_HEAD

      - name: Run tests
        {#- Escape curly braces for Cookiecutter. -#}
        {%- raw %}
        run: uv run --python ${{ matrix.python-version }} pytest
        {%- endraw %}
