name: Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-deps-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-deps-image.yaml

  deploy:
    needs: build-deps-image
    runs-on: ubuntu-latest
    {#- Escape curly braces for Cookiecutter. -#}
    {%- raw %}
    container: ${{ needs.build-deps-image.outputs.image }}
    {%- endraw %}
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and deploy docs
        run: ./workflow.cmd document.deploy-github
