name: Build dependency image
description: Build and publish the deps container image to GHCR if needed.
outputs:
  image:
    description: Full GHCR image reference for the deps image.
    {#- Escape curly braces for Cookiecutter. -#}
    {%- raw %}
    value: ${{ steps.image-ref.outputs.image }}
    {%- endraw %}
runs:
  using: composite
  steps:
    - name: Publish deps image
      run: ./workflow.cmd container publish
      shell: bash

    - name: Set image reference
      id: image-ref
      run: echo "image=$(cat .deps-image)" >> "$GITHUB_OUTPUT"
      shell: bash
