default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint code
        entry: ./workflow lint
        language: system
        pass_filenames: false
        files: ^(_CI/tasks/|src/|tests/).*\.py$
        stages: [pre-commit]
      - id: test
        name: Run tests
        entry: ./workflow test
        language: system
        pass_filenames: false
        files: ^(src/|tests/).*\.py$
        stages: [pre-commit]
      - id: lint-commit
        name: Lint commit message
        description: "Example: feat: added new feature"
        entry: sh -c './workflow lint.commitizen --commit-msg-file="$1"' --
        language: system
        pass_filenames: true
        stages: [commit-msg]
